# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('subnet', models.CharField(max_length=15)),
                ('gateway', models.CharField(max_length=15)),
                ('DNS', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Machine'),
        ),
    ]
